export default [
  {
    id: 1,
    title: 'COM_CONCOLE_MANAGER_TITLE',
    path: '/console',
    type: 'menu',
    component: 'console/edit',
    icon: 'home',
    visible: 1,
    assets: [],
  },
  {
    id: 2,
    title: 'COM_HOME_TITLE',
    path: '/home',
    type: 'alias',
    component: '',
    icon: 'copy',
    visible: 1,
    assets: [
      {
        id: 1,
        title: 'COM_SLIDESHOW_MANAGER_TITLE',
        path: 'slideshow',
        component: 'home/slideshow/list',
        type: 'menu',
        icon: 'images',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 162,
            name: '取得slideshow',
            method: 'getSlideshow',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 163,
            name: '新增slideshow',
            method: 'addSlideshow',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 164,
            name: '編輯slideshow',
            method: 'editSlideshow',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 165,
            name: '刪除slideshow',
            method: 'deleteSlideshow',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 166,
            name: '搜尋slideshow',
            method: 'searchSlideshow',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 167,
            name: '更新slideshow狀態',
            method: 'stateSlideshow',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 168,
            name: '回存slideshow',
            method: 'restoreSlideshow',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
    ],
  },
  {
    id: 3,
    title: 'COM_BRANDS_TITLE',
    path: '/brands',
    type: 'alias',
    component: '',
    icon: 'copy',
    visible: 1,
    assets: [
      {
        id: 2,
        title: 'COM_BRANDS_MANAGER_TITLE',
        path: 'manager',
        component: 'brands/manager/list',
        type: 'menu',
        icon: 'sliders-h',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 139,
            name: '取得品牌',
            method: 'getBrand',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 140,
            name: '新增品牌',
            method: 'addBrand',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 141,
            name: '編輯品牌',
            method: 'editBrand',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 142,
            name: '刪除品牌',
            method: 'deleteBrand',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 143,
            name: '搜尋品牌',
            method: 'searchBrand',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 144,
            name: '更新品牌狀態',
            method: 'stateBrand',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 145,
            name: '回存品牌',
            method: 'restoreBrand',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
    ],
  },
  {
    id: 4,
    title: 'COM_PRODUCTS_TITLE',
    path: '/products',
    type: 'alias',
    component: '',
    icon: 'copy',
    visible: 1,
    assets: [
      {
        id: 3,
        title: 'COM_PRODUCTS_CATEGORY_MANAGER_TITLE',
        path: 'category',
        component: 'products/category/list',
        type: 'menu',
        icon: 'file-alt',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 146,
            name: '取得產品類別',
            method: 'getProductCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 147,
            name: '取得產品類別列表',
            method: 'getTreeProductCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 148,
            name: '新增產品類別',
            method: 'addProductCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 149,
            name: '編輯產品類別',
            method: 'editProductCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 150,
            name: '刪除產品類別',
            method: 'deleteProductCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 151,
            name: '搜尋產品類別',
            method: 'searchProductCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 152,
            name: '更新產品類別狀態',
            method: 'stateProductCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 153,
            name: '回存產品類別',
            method: 'restoreProductCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 154,
            name: '排序產品類別',
            method: 'orderingProductCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
      {
        id: 4,
        title: 'COM_PRODUCTS_DATA_MANAGER_TITLE',
        path: 'data',
        component: 'products/data/list',
        type: 'menu',
        icon: 'file-alt',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 155,
            name: '取得產品資料',
            method: 'getProduct',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 156,
            name: '新增產品資料',
            method: 'addProduct',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 157,
            name: '編輯產品資料',
            method: 'editProduct',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 158,
            name: '刪除產品資料',
            method: 'deleteProduct',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 159,
            name: '搜尋產品資料',
            method: 'searchProduct',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 160,
            name: '更新產品資料狀態',
            method: 'stateProduct',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 161,
            name: '回存產品資料',
            method: 'restoreProduct',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
    ],
  },
  {
    id: 5,
    title: 'COM_CONTRACT_FILES_TITLE',
    path: '/contract',
    type: 'alias',
    component: '',
    icon: 'copy',
    visible: 1,
    assets: [
      {
        id: 5,
        title: 'COM_CONTRACT_FILES_CATEGORY_MANAGER_TITLE',
        path: 'category',
        component: 'contract_files/category/list',
        type: 'menu',
        icon: 'copy',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 125,
            name: '取得檔案類型',
            method: 'getFileCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 126,
            name: '新增檔案類型',
            method: 'addFileCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 127,
            name: '編輯檔案類型',
            method: 'editFileCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 129,
            name: '搜尋檔案類型',
            method: 'searchFileCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 130,
            name: '更新檔案類型狀態',
            method: 'stateFileCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 131,
            name: '回存檔案類型',
            method: 'restoreFileCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
      {
        id: 6,
        title: 'COM_CONTRACT_FILES_MANAGER_TITLE',
        path: 'manager',
        component: 'contract_files/manager/list',
        type: 'menu',
        icon: 'copy',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 132,
            name: '取得檔案',
            method: 'getFile',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 133,
            name: '新增檔案',
            method: 'addFile',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 134,
            name: '編輯檔案',
            method: 'editFile',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 136,
            name: '搜尋檔案',
            method: 'searchFile',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 137,
            name: '更新檔案狀態',
            method: 'stateFile',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 138,
            name: '回存檔案',
            method: 'restoreFile',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
    ],
  },
  {
    id: 6,
    title: 'COM_INDUSTRY_TITLE',
    path: '/industry',
    type: 'alias',
    component: '',
    icon: 'copy',
    visible: 1,
    assets: [
      {
        id: 7,
        title: 'COM_INDUSTRY_MANAGER_TITLE',
        path: 'manager',
        component: 'industry/manager/list',
        type: 'menu',
        icon: 'folder-open',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 169,
            name: '取得產業分類',
            method: 'getIndustryCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 170,
            name: '新增產業分類',
            method: 'addIndustryCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 171,
            name: '編輯產業分類',
            method: 'editIndustryCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 172,
            name: '刪除產業分類',
            method: 'deleteIndustryCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 173,
            name: '搜尋產業分類',
            method: 'searchIndustryCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 174,
            name: '更新產業分類狀態',
            method: 'stateIndustryCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 175,
            name: '回存產業分類',
            method: 'restoreIndustryCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
    ],
  },
  {
    id: 7,
    title: 'COM_SOLUTIONS_TITLE',
    path: '/solutions',
    type: 'alias',
    component: '',
    icon: 'copy',
    visible: 1,
    assets: [
      {
        id: 8,
        title: 'COM_SOLUTIONS_MANAGER_TITLE',
        path: 'manager',
        component: 'solutions/manager/list',
        type: 'menu',
        icon: 'folder-open',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 176,
            name: '取得解決方案',
            method: 'getSolution',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 177,
            name: '新增解決方案',
            method: 'addSolution',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 178,
            name: '編輯解決方案',
            method: 'editSolution',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 179,
            name: '刪除解決方案',
            method: 'deleteSolution',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 180,
            name: '搜尋解決方案',
            method: 'searchSolution',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 181,
            name: '更新解決方案狀態',
            method: 'stateSolution',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 182,
            name: '回存解決方案',
            method: 'restoreSolution',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
      {
        id: 9,
        title: 'COM_SOLUTIONS_CATEGORY_MANAGER_TITLE',
        path: 'category',
        component: 'solutions/category/list',
        type: 'menu',
        icon: 'folder-open',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 183,
            name: '取得方案類別',
            method: 'getSolutionCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 184,
            name: '新增方案類別',
            method: 'addSolutionCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 185,
            name: '編輯方案類別',
            method: 'editSolutionCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 186,
            name: '刪除方案類別',
            method: 'deleteSolutionCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 187,
            name: '搜尋方案類別',
            method: 'searchSolutionCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 188,
            name: '更新方案類別狀態',
            method: 'stateSolutionCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 189,
            name: '回存方案類別',
            method: 'restoreSolutionCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
    ],
  },
  {
    id: 8,
    title: 'COM_SUCCESS_TITLE',
    path: '/success',
    type: 'alias',
    component: '',
    icon: 'copy',
    visible: 1,
    assets: [
      {
        id: 10,
        title: 'COM_SUCCESS_MANAGER_TITLE',
        path: 'manager',
        component: 'success/manager/list',
        type: 'menu',
        icon: 'copy',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 190,
            name: '取得成功案例',
            method: 'getCase',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 191,
            name: '新增成功案例',
            method: 'addCase',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 192,
            name: '編輯成功案例',
            method: 'editCase',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 193,
            name: '刪除成功案例',
            method: 'deleteCase',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 194,
            name: '搜尋成功案例',
            method: 'searchCase',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 195,
            name: '更新成功案例狀態',
            method: 'stateCase',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 196,
            name: '回存成功案例',
            method: 'restoreCase',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
    ],
  },
  {
    id: 19,
    title: 'COM_COURSE_ACTIVITY_MANAGER_TITLE',
    path: '/course_activity',
    type: 'alias',
    component: '',
    icon: 'copy',
    visible: 1,
    assets: [
      {
        id: 30,
        title: 'COM_COURSE_MANAGER_TITLE',
        path: 'course',
        component: 'course_activity/course/list',
        type: 'menu',
        icon: 'sitemap',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 293,
            name: '取得事件',
            method: 'getEvent',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 294,
            name: '新增事件',
            method: 'addEvent',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 295,
            name: '編輯事件',
            method: 'editEvent',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 296,
            name: '刪除事件',
            method: 'deleteEvent',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 297,
            name: '搜尋事件',
            method: 'searchEvent',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 298,
            name: '更新事件狀態',
            method: 'stateEvent',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 299,
            name: '回存事件',
            method: 'restoreEvent',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 300,
            name: '排序事件',
            method: 'orderingEvent',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 303,
            name: '搜尋事件報名人員',
            method: 'searchRegistration',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 304,
            name: '匯出事件報名表',
            method: 'exportEventRegistrationForm',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 305,
            name: '匯入事件報名資料',
            method: 'importEventRegistration',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 306,
            name: '匯出事件報名資料',
            method: 'exportEventRegistration',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 317,
            name: '排序事件分類',
            method: 'orderingEvent',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 327,
            name: '排序事件',
            method: 'orderingEvent',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
      {
        id: 31,
        title: 'COM_ACTIVITY_MANAGER_TITLE',
        path: 'activity',
        component: 'course_activity/activity/list',
        type: 'menu',
        icon: 'sitemap',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 293,
            name: '取得事件',
            method: 'getEvent',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 294,
            name: '新增事件',
            method: 'addEvent',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 295,
            name: '編輯事件',
            method: 'editEvent',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 296,
            name: '刪除事件',
            method: 'deleteEvent',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 297,
            name: '搜尋事件',
            method: 'searchEvent',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 298,
            name: '更新事件狀態',
            method: 'stateEvent',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 299,
            name: '回存事件',
            method: 'restoreEvent',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 300,
            name: '排序事件',
            method: 'orderingEvent',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 303,
            name: '搜尋事件報名人員',
            method: 'searchRegistration',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 317,
            name: '排序事件分類',
            method: 'orderingEvent',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 327,
            name: '排序事件',
            method: 'orderingEvent',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
      {
        id: 32,
        title: 'COM_SIGNUP_MANAGER_TITLE',
        path: 'signup',
        component: 'course_activity/signup/list',
        type: 'menu',
        icon: 'sitemap',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 337,
            name: '取得訂單',
            method: 'getOrder',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 338,
            name: '搜尋訂單',
            method: 'searchOrder',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 339,
            name: '審核訂單',
            method: 'reviewOrder',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 342,
            name: '報到訂單項目',
            method: 'checkinOrderItem',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
      {
        id: 33,
        title: 'COM_PERSONNEL_MANAGER_TITLE',
        path: 'personnel',
        component: 'course_activity/personnel/edit',
        type: 'menu',
        icon: 'sitemap',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 343,
            name: '取得人事身份',
            method: 'getPersonnelCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 344,
            name: '新增人事身份',
            method: 'addPersonnelCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 345,
            name: '編輯人事身份',
            method: 'editPersonnelCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 346,
            name: '刪除人事身份',
            method: 'deletePersonnelCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 347,
            name: '搜尋人事身份',
            method: 'searchPersonnelCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 348,
            name: '更新人事身份狀態',
            method: 'statePersonnelCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 349,
            name: '回存人事身份',
            method: 'restorePersonnelCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 351,
            name: '取得人事',
            method: 'getPersonnel',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 352,
            name: '新增人事',
            method: 'addPersonnel',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 353,
            name: '編輯人事',
            method: 'editPersonnel',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 354,
            name: '刪除人事',
            method: 'deletePersonnel',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 355,
            name: '搜尋人事',
            method: 'searchPersonnel',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 356,
            name: '更新人事狀態',
            method: 'statePersonnel',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 357,
            name: '回存人事',
            method: 'restorePersonnel',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
      {
        id: 34,
        title: 'COM_COURSE_ACTIVITY_TICKET_MANAGER_TITLE',
        path: 'ticket',
        component: 'course_activity/ticket/list',
        type: 'menu',
        icon: 'sitemap',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 283,
            name: '取得優惠券群組',
            method: 'getCouponGroup',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 284,
            name: '新增優惠券群組',
            method: 'addCouponGroup',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 285,
            name: '編輯優惠券群組',
            method: 'editCouponGroup',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 286,
            name: '刪除優惠券群組',
            method: 'deleteCouponGroup',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 287,
            name: '搜尋優惠券群組',
            method: 'searchCouponGroup',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 288,
            name: '更新優惠券群組狀態',
            method: 'stateCouponGroup',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 289,
            name: '回存優惠券群組',
            method: 'restoreCouponGroup',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
      {
        id: 35,
        title: 'COM_COURSE_ACTIVITY_NOTIFICATION_MANAGER_TITLE',
        path: 'notification',
        component: 'course_activity/notification/edit',
        type: 'menu',
        icon: 'sitemap',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 335,
            name: '搜尋通知紀錄',
            method: 'searchNotificationRecord',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
    ],
  },
  {
    id: 20,
    title: 'COM_FRONT_DESK',
    path: '/frontdesk',
    type: 'alias',
    component: '',
    icon: 'copy',
    visible: 1,
    assets: [
      {
        id: 36,
        title: 'COM_FRONT_DESK_MANAGER_TITLE',
        path: 'frontdesk',
        component: 'frontdesk/checkin',
        type: 'menu',
        icon: 'sitemap',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 366,
            name: '取得訂單QRCode資訊',
            method: 'getOrderQrcodeByCode',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 367,
            name: '報到QRCode場次或餐食',
            method: 'checkinOrderQrcode',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
    ],
  },
  {
    id: 9,
    title: 'COM_DOWNLOAD_FILES_TITLE',
    path: '/download_files',
    type: 'alias',
    component: '',
    icon: 'copy',
    visible: 1,
    assets: [
      {
        id: 11,
        title: 'COM_FILES_CATEGORY_MANAGER_TITLE',
        path: 'category',
        component: 'files/category/list',
        type: 'menu',
        icon: 'copy',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 125,
            name: '取得檔案類型',
            method: 'getFileCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 126,
            name: '新增檔案類型',
            method: 'addFileCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 127,
            name: '編輯檔案類型',
            method: 'editFileCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 129,
            name: '搜尋檔案類型',
            method: 'searchFileCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 130,
            name: '更新檔案類型狀態',
            method: 'stateFileCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 131,
            name: '回存檔案類型',
            method: 'restoreFileCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
      {
        id: 12,
        title: 'COM_FILES_MANAGER_TITLE',
        path: 'files',
        component: 'files/manager/list',
        type: 'menu',
        icon: 'copy',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 132,
            name: '取得檔案',
            method: 'getFile',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 133,
            name: '新增檔案',
            method: 'addFile',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 134,
            name: '編輯檔案',
            method: 'editFile',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 136,
            name: '搜尋檔案',
            method: 'searchFile',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 137,
            name: '更新檔案狀態',
            method: 'stateFile',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 138,
            name: '回存檔案',
            method: 'restoreFile',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
    ],
  },
  {
    id: 10,
    title: 'COM_NEWS_TITLE',
    path: '/news',
    type: 'alias',
    component: '',
    icon: 'copy',
    visible: 1,
    assets: [
      {
        id: 13,
        title: 'COM_NEWS_MANAGER_TITLE',
        path: 'manager',
        component: 'news/manager/list',
        type: 'menu',
        icon: 'copy',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 197,
            name: '取得最新消息',
            method: 'getBulletin',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 198,
            name: '新增最新消息',
            method: 'addBulletin',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 199,
            name: '編輯最新消息',
            method: 'editBulletin',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 200,
            name: '刪除最新消息',
            method: 'deleteBulletin',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 201,
            name: '搜尋最新消息',
            method: 'searchBulletin',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 202,
            name: '更新最新消息狀態',
            method: 'stateBulletin',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 203,
            name: '回存最新消息',
            method: 'restoreBulletin',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 204,
            name: '精選最新消息',
            method: 'featuredBulletin',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
      {
        id: 14,
        title: 'COM_NEWS_PROMOTION_MANAGER_TITLE',
        path: 'promotion',
        component: 'news/promotion/list',
        type: 'menu',
        icon: 'copy',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 205,
            name: '取得促銷訊息',
            method: 'getPromotion',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 206,
            name: '新增促銷訊息',
            method: 'addPromotion',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 207,
            name: '編輯促銷訊息',
            method: 'editPromotion',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 208,
            name: '刪除促銷訊息',
            method: 'deletePromotion',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 209,
            name: '搜尋促銷訊息',
            method: 'searchPromotion',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 210,
            name: '更新促銷訊息狀態',
            method: 'statePromotion',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 211,
            name: '回存促銷訊息',
            method: 'restorePromotion',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 212,
            name: '精選促銷訊息',
            method: 'featuredPromotion',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
    ],
  },
  {
    id: 11,
    title: 'COM_VIDEOS_TITLE',
    path: '/videos',
    type: 'alias',
    component: '',
    icon: 'copy',
    visible: 1,
    assets: [
      {
        id: 15,
        title: 'COM_VIDEOS_MANAGER_TITLE',
        path: 'manager',
        component: 'videos/manager/list',
        type: 'menu',
        icon: 'copy',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 213,
            name: '取得零壹影片',
            method: 'getVideo',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 214,
            name: '新增零壹影片',
            method: 'addVideo',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 215,
            name: '編輯零壹影片',
            method: 'editVideo',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 216,
            name: '刪除零壹影片',
            method: 'deleteVideo',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 217,
            name: '搜尋零壹影片',
            method: 'searchVideo',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 218,
            name: '更新零壹影片狀態',
            method: 'stateVideo',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 219,
            name: '回存零壹影片',
            method: 'restoreVideo',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 220,
            name: '精選零壹影片',
            method: 'featuredVideo',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
    ],
  },
  {
    id: 12,
    title: 'COM_STATIC_TITLE',
    path: '/static',
    type: 'alias',
    component: '',
    icon: 'copy',
    visible: 1,
    assets: [
      {
        id: 16,
        title: 'COM_MEMORABILIA_MANAGER_TITLE',
        path: 'memorabilia',
        component: 'static/memorabilia/list',
        type: 'menu',
        icon: 'sitemap',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 221,
            name: '取得零壹大事紀',
            method: 'getMemorabilia',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 222,
            name: '新增零壹大事紀',
            method: 'addMemorabilia',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 223,
            name: '編輯零壹大事紀',
            method: 'editMemorabilia',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 224,
            name: '刪除零壹大事紀',
            method: 'deleteMemorabilia',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 225,
            name: '搜尋零壹大事紀',
            method: 'searchMemorabilia',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 226,
            name: '更新零壹大事紀狀態',
            method: 'stateMemorabilia',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 227,
            name: '回存零壹大事紀',
            method: 'restoreMemorabilia',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
      {
        id: 17,
        title: 'COM_FINANCE_MANAGER_TITLE',
        path: 'finance',
        component: 'static/finance/list',
        type: 'menu',
        icon: 'sitemap',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 228,
            name: '取得財務資訊',
            method: 'getFinance',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 229,
            name: '新增財務資訊',
            method: 'addFinance',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 230,
            name: '編輯財務資訊',
            method: 'editFinance',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 231,
            name: '刪除財務資訊',
            method: 'deleteFinance',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 232,
            name: '搜尋財務資訊',
            method: 'searchFinance',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 233,
            name: '更新財務資訊狀態',
            method: 'stateFinance',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 234,
            name: '回存財務資訊',
            method: 'restoreFinance',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
      {
        id: 18,
        title: 'COM_RULES_MANAGER_TITLE',
        path: 'rules',
        component: 'static/rules/list',
        type: 'menu',
        icon: 'sitemap',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 235,
            name: '取得重要規章',
            method: 'getRules',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 236,
            name: '新增重要規章',
            method: 'addRules',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 237,
            name: '編輯重要規章',
            method: 'editRules',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 238,
            name: '刪除重要規章',
            method: 'deleteRules',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 239,
            name: '搜尋重要規章',
            method: 'searchRules',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 240,
            name: '更新重要規章狀態',
            method: 'stateRules',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 241,
            name: '回存重要規章',
            method: 'restoreRules',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
      {
        id: 19,
        title: 'COM_STOCKHOLDER_MANAGER_TITLE',
        path: 'stockholder',
        component: 'static/stockholder/list',
        type: 'menu',
        icon: 'sitemap',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 242,
            name: '取得股東專欄',
            method: 'getStockholder',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 243,
            name: '新增股東專欄',
            method: 'addStockholder',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 244,
            name: '編輯股東專欄',
            method: 'editStockholder',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 245,
            name: '刪除股東專欄',
            method: 'deleteStockholder',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 246,
            name: '搜尋股東專欄',
            method: 'searchStockholder',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 247,
            name: '更新股東專欄狀態',
            method: 'stateStockholder',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 248,
            name: '回存股東專欄',
            method: 'restoreStockholder',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
    ],
  },
  {
    id: 13,
    title: 'COM_KEYWORDS_TITLE',
    path: '/keywords',
    type: 'alias',
    component: '',
    icon: 'copy',
    visible: 1,
    assets: [
      {
        id: 20,
        title: 'COM_KEYWORDS_MANAGER_TITLE',
        path: 'manager',
        component: 'keywords/manager/list',
        type: 'menu',
        icon: 'copy',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 108,
            name: '取得關鍵字',
            method: 'getTag',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 109,
            name: '新增關鍵字',
            method: 'addTag',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 110,
            name: '編輯關鍵字',
            method: 'editTag',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 111,
            name: '刪除關鍵字',
            method: 'deleteTag',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 112,
            name: '搜尋關鍵字',
            method: 'searchTag',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 113,
            name: '更新關鍵字狀態',
            method: 'stateTag',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 114,
            name: '回存關鍵字',
            method: 'restoreTag',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 115,
            name: '排序關鍵字',
            method: 'orderingTag',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
    ],
  },
  {
    id: 14,
    title: 'COM_SUBSCRIPTION_TITLE',
    path: '/subscription',
    type: 'alias',
    component: '',
    icon: 'copy',
    visible: 1,
    assets: [
      {
        id: 21,
        title: 'COM_SUBSCRIPTION_CATEGORY_MANAGER_TITLE',
        path: 'category',
        component: 'subscription/category/list',
        type: 'menu',
        icon: 'copy',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 249,
            name: '取得電子報類別',
            method: 'getNewsletterCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 250,
            name: '新增電子報類別',
            method: 'addNewsletterCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 251,
            name: '編輯電子報類別',
            method: 'editNewsletterCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 252,
            name: '刪除電子報類別',
            method: 'deleteNewsletterCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 253,
            name: '搜尋電子報類別',
            method: 'searchNewsletterCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 254,
            name: '更新電子報類別狀態',
            method: 'stateNewsletterCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 255,
            name: '回存電子報類別',
            method: 'restoreNewsletterCategory',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
      {
        id: 22,
        title: 'COM_SUBSCRIPTION_CONTENT_MANAGER_TITLE',
        path: 'content',
        component: 'subscription/content/list',
        type: 'menu',
        icon: 'copy',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 256,
            name: '取得電子報',
            method: 'getNewsletter',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 257,
            name: '新增電子報',
            method: 'addNewsletter',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 258,
            name: '編輯電子報',
            method: 'editNewsletter',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 259,
            name: '刪除電子報',
            method: 'deleteNewsletter',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 260,
            name: '搜尋電子報',
            method: 'searchNewsletter',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 261,
            name: '更新電子報狀態',
            method: 'stateNewsletter',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 262,
            name: '回存電子報',
            method: 'restoreNewsletter',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 263,
            name: '發佈電子報',
            method: 'publishNewsletter',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
      {
        id: 23,
        title: 'COM_SUBSCRIPTION_MANAGER_TITLE',
        path: 'manager',
        component: 'subscription/manager/list',
        type: 'menu',
        icon: 'copy',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 264,
            name: '取得電子報訂閱',
            method: 'getNewsletterSubscription',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 265,
            name: '新增電子報訂閱',
            method: 'addNewsletterSubscription',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 266,
            name: '編輯電子報訂閱',
            method: 'editNewsletterSubscription',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 267,
            name: '刪除電子報訂閱',
            method: 'deleteNewsletterSubscription',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 268,
            name: '搜尋電子報訂閱',
            method: 'searchNewsletterSubscription',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 269,
            name: '更新電子報訂閱狀態',
            method: 'stateNewsletterSubscription',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 270,
            name: '回存電子報訂閱',
            method: 'restoreNewsletterSubscription',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 271,
            name: '匯出電子報訂閱',
            method: 'exportNewsletterSubscription',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
    ],
  },
  {
    id: 15,
    title: 'COM_MEMBERS_TITLE',
    path: '/members',
    type: 'alias',
    component: '',
    icon: 'copy',
    visible: 1,
    assets: [
      {
        id: 24,
        title: 'COM_MEMBERS_MANAGER_TITLE',
        path: 'manager',
        component: 'members/manager/list',
        type: 'menu',
        icon: 'copy',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 22,
            name: '取得會員',
            method: 'getUser',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 24,
            name: '編輯會員',
            method: 'editUser',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 26,
            name: '搜尋會員',
            method: 'searchUser',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 27,
            name: '封鎖會員',
            method: 'blockUser',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 32,
            name: '搜尋會員群組',
            method: 'searchUserGroup',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
      {
        id: 25,
        title: 'COM_MEMBERS_TAX_MANAGER_TITLE',
        path: 'tax',
        component: 'members/tax/list',
        type: 'menu',
        icon: 'copy',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 277,
            name: '取得統編資料',
            method: 'getCompany',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 278,
            name: '新增統編資料',
            method: 'addCompany',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 279,
            name: '編輯統編資料',
            method: 'editCompany',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 280,
            name: '刪除統編資料',
            method: 'deleteCompany',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 281,
            name: '搜尋統編資料',
            method: 'searchCompany',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 282,
            name: '回存統編資料',
            method: 'restoreCompany',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
    ],
  },
  {
    id: 16,
    title: 'COM_PERMISSIONS_TITLE',
    path: '/permissions',
    type: 'alias',
    component: '',
    icon: 'copy',
    visible: 1,
    assets: [
      {
        id: 26,
        title: 'COM_PERMISSIONS_GROUP_MANAGER_TITLE',
        path: 'group',
        component: 'permissions/group/list',
        type: 'menu',
        icon: 'copy',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 28,
            name: '取得會員群組',
            method: 'getUserGroup',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 29,
            name: '新增會員群組',
            method: 'addUserGroup',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 30,
            name: '編輯會員群組',
            method: 'editUserGroup',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 31,
            name: '刪除會員群組',
            method: 'deleteUserGroup',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 32,
            name: '搜尋會員群組',
            method: 'searchUserGroup',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
      {
        id: 27,
        title: 'COM_PERMISSIONS_ACCOUNT_MANAGER_TITLE',
        path: 'account',
        component: 'permissions/account/list',
        type: 'menu',
        icon: 'copy',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 22,
            name: '取得會員',
            method: 'getUser',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 23,
            name: '新增會員',
            method: 'addUser',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 24,
            name: '編輯會員',
            method: 'editUser',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 25,
            name: '刪除會員',
            method: 'deleteUser',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 26,
            name: '搜尋會員',
            method: 'searchUser',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 27,
            name: '封鎖會員',
            method: 'blockUser',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
    ],
  },
  {
    id: 17,
    title: 'COM_COMMENTS_TITLE',
    path: '/comments',
    type: 'alias',
    component: '',
    icon: 'copy',
    visible: 1,
    assets: [
      {
        id: 28,
        title: 'COM_COMMENTS_MANAGER_TITLE',
        path: 'manager',
        component: 'comments/manager/list',
        type: 'menu',
        icon: 'copy',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 272,
            name: '取得顧客留言',
            method: 'getCustomerMessage',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 273,
            name: '編輯顧客留言',
            method: 'editCustomerMessage',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 274,
            name: '搜尋顧客留言',
            method: 'searchCustomerMessage',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 275,
            name: '回存顧客留言',
            method: 'restoreCustomerMessage',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 276,
            name: '回覆顧客留言',
            method: 'storeCustomerMessageReply',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
    ],
  },
  {
    id: 18,
    title: 'COM_SEO_TITLE',
    path: '/seo',
    type: 'alias',
    component: '',
    icon: 'copy',
    visible: 1,
    assets: [
      {
        id: 29,
        title: 'COM_SEO_EDIT_TITLE',
        path: '',
        component: 'seo/manager/edit',
        type: 'menu',
        icon: 'copy',
        showNav: 1,
        visible: 1,
        apis: [
          {
            id: 41,
            name: '取得全站設定',
            method: 'getSetting',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
          {
            id: 42,
            name: '編輯全站設定',
            method: 'editSetting',
            hidden: 0,
            disabled: 0,
            checked: 1,
          },
        ],
      },
    ],
  },
]
