name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:

  install-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install And Build
      run: |
        cd cms-frontend
        npm i
        npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: ../public
        token: ${{ secrets.ACCESS_TOKEN }}
        # BUILD_SCRIPT: cd cms-frontend && npm i && npm run build